server:
  port: 8103

spring:
  application:
    name: component-file
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 5
    validationQuery: SELECT 1 FROM DUAL
    initialSize: 5
    maxWait: 60000
    filters: stat,wall,log4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.159.144.194:3306/test?useSSL=false&serverTimezone=GMT&allowMultiQueries=true&characterEncoding=UTF-8
    maxPoolPreparedStatementPerConnectionSize: 20
    password: khtestdb_1022
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    username: khtestuser
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:mybatis-config.xml

logging:
  file: ./log/${spring.application.name}.log