server:
  port: 8101

apache:
  rocketmq:
    # NameServer地址
    namesrvAddr: 127.0.0.1:9876
    # 生产者
    producer:
      producerGroup: producer
    # 消费者
    consumer:
      comsumerGroup: comsumer





