server:
  port: 8101

apache:
  rocketmq:
    # NameServer地址
    namesrvAddr: 192.168.0.52:9876
    # 生产者
    producer:
      producerGroup: producer
    # 消费者
    consumer:
      comsumerGroup: comsumer





