server:
  port: 9010

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 45
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: eurka-server