server:
  port: 8002

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registerServer1:9010/eureka/,http://registerServer2:9010/eureka/

spring:
  application:
    name: service-order-manage

apache:
  rocketmq:
    namesrvAddr: 127.0.0.1:9876
    producer:
      producerGroup: producer
    consumer:
      comsumerGroup: comsumer

logging:
  file: ./log/${spring.application.name}.log