server:
  port: 8001

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registerServer1:9010/eureka/,http://registerServer2:9010/eureka/

spring:
  application:
    name: service-member-manage
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 5
    validationQuery: SELECT 1 FROM DUAL
    initialSize: 5
    maxWait: 60000
    filters: stat,wall,log4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.159.144.194:3306/test?useSSL=false&serverTimezone=GMT&allowMultiQueries=true&characterEncoding=UTF-8
    maxPoolPreparedStatementPerConnectionSize: 20
    password: khtestdb_1022
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    username: khtestuser
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # 最大连接数据库连接数,设0为没有限制
        max-active: 8
        # 最大等待连接中的数量,设0为没有限制
        max-idle: 8
        # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
        max-wait: -1ms
        # 最小等待连接中的数量,设0为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  file: ./log/${spring.application.name}.log

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:mybatis-config.xml

